### ISSUE TITLE
Error abort on C99 batch import

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#1094]
A modification for issue #809 in version 3.32-12 may now cause an error abort on importing C files in batch mode, which is due to an insufficiently initialized list of split keywords during diagram post-processing.
(Import in interactive mode works, though, without showing this problem).

This is the stacktrace written to the error stream:
```
Exception in thread "main" java.lang.ArrayIndexOutOfBoundsException: 4 >= 0
	at java.base/java.util.Vector.elementAt(Vector.java:466)
	at lu.fisch.structorizer.elements.Root.getUsedVarNames(Root.java:2829)
	at lu.fisch.structorizer.elements.Root.getUsedVarNames(Root.java:2773)
	at lu.fisch.structorizer.parsers.CPreParser.subclassUpdateRoot(CPreParser.java:1783)
	at lu.fisch.structorizer.parsers.CodeParser.parse(CodeParser.java:885)
	at Structorizer.parse(Structorizer.java:1156)
	at Structorizer.main(Structorizer.java:362) 
```

**Comment by codemanyak** [comment]
Bugfix ready for version 3.32-13
