### ISSUE TITLE
GUI bug

### ISSUE THREAD

**Issue by pre55** [fesch/Structorizer.Desktop#119]
also at the new version:
structorizer_3_23
win7 enterprise

![GUI BUT](http://abload.de/img/structorizerguibugzguby.png)

**Comment by codemanyak** [comment]
Interesting. Never experienced that (I'm working on Windows 7).
Apparently, no single icon is found or properly set up.
Did you download the zip file or use the Webstart installation?
In the first case, I wonder whether or not you obtain some error messages if you start Structorizer from the command line. To do so, please open the MSDOS window (e.g. by typing "cmd" at the start menu line), then navigate to the extracted Structorizer folder and type the following command (actually the content of Structorizer.sh), if you wouldn't mind:
java -jar Structorizer.app/Contents/Resources/Java/Structorizer.jar
If you happen to see some error messages, then it would be of great help copying them hitherto.
Thanks in advance.

**Comment by codemanyak** [comment]
Some more observations:

- Seeing that the title doesn't show the Structorizer version number, you must be using a version prior to the most recent development version 3.23-14, right? Possibly release 3.23-00? (Don't get me wrong: This is not a known issue for any version of Structorizer, obsolete or not...)
- Where did you obtain the version from? http://Structorizer.fisch.lu (or e.g. Chip.de or heise.de)?
- Do you use a 32 bit or 64 bit OS version (has never played a role, though)?
- What a screen resolution have you configured on your computer? Have you already tried with a different one? (This is not meant to be the solution for using Structorizer, of course, but just a try to find out what's going wrong at your site.)

**Comment by pre55** [comment]
This issue, I mentioned, appeared at my work PC at higher Res. 
I'll send you my works PCs details, from my work.

But now the same GUI bug appears at my personal laptop (Win10pro, x64, Res:1920x1080)
![Win10Pro_x64_GUI_bug](http://abload.de/img/structorizer_gui_bug_sdu68.png)
I downloaded http://www.fisch.lu/Php/download.php?file=structorizer_3_23.zip from http://structorizer.fisch.lu/index.php?include=downloads.

executed following code:
java -jar Structorizer.app/Contents/Resources/Java/Structorizer.jar
`C:\DATA\Structorizer>java -jar Structorizer.app/Contents/Resources/Java/Structorizer.jar
Error parsing input bugger: java.io.IOException: Stream closed
java.io.IOException: Stream closed
        at java.io.BufferedInputStream.getInIfOpen(Unknown Source)
        at java.io.BufferedInputStream.fill(Unknown Source)
        at java.io.BufferedInputStream.read(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager$RewindableInputStream.read(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLEntityManager.setupCurrentEntity(Unknown Source)
        at com.sun.org.apache.xerces.internal.impl.XMLVersionDetector.determineDocVersion(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
        at javax.xml.parsers.SAXParser.parse(Unknown Source)
        at lu.fisch.structorizer.parsers.GENParser.parse(GENParser.java:89)
        at lu.fisch.structorizer.gui.Menu.create(Menu.java:287)
        at lu.fisch.structorizer.gui.Menu.<init>(Menu.java:849)
        at lu.fisch.structorizer.gui.Mainform.create(Mainform.java:147)
        at lu.fisch.structorizer.gui.Mainform.<init>(Mainform.java:546)
        at lu.fisch.structorizer.gui.Mainform.<init>(Mainform.java:539)
        at Structorizer.main(Structorizer.java:41)
java.lang.NullPointerException
        at java.io.Reader.<init>(Unknown Source)
        at java.io.InputStreamReader.<init>(Unknown Source)
        at lu.fisch.structorizer.gui.LangDialog.setLang(LangDialog.java:80)
        at lu.fisch.structorizer.gui.Menu.setLangLocal(Menu.java:666)
        at lu.fisch.structorizer.gui.Mainform.setLang(Mainform.java:477)
        at lu.fisch.structorizer.gui.Mainform.loadFromINI(Mainform.java:245)
        at lu.fisch.structorizer.gui.Mainform.create(Mainform.java:204)
        at lu.fisch.structorizer.gui.Mainform.<init>(Mainform.java:546)
        at lu.fisch.structorizer.gui.Mainform.<init>(Mainform.java:539)
        at Structorizer.main(Structorizer.java:41)
java.lang.NullPointerException
Exception in thread "main" java.lang.NullPointerException
        at java.io.Reader.<init>(Unknown Source)
        at java.io.InputStreamReader.<init>(Unknown Source)
        at lu.fisch.structorizer.gui.LangDialog.setLang(LangDialog.java:80)
        at lu.fisch.structorizer.gui.Menu.setLangLocal(Menu.java:666)
        at lu.fisch.structorizer.gui.Mainform.setLang(Mainform.java:477)
        at lu.fisch.structorizer.gui.Mainform.create(Mainform.java:205)
        at lu.fisch.structorizer.gui.Mainform.<init>(Mainform.java:546)
        at lu.fisch.structorizer.gui.Mainform.<init>(Mainform.java:539)
        at Structorizer.main(Structorizer.java:41)`

**Comment by fesch** [comment]
Seams like the icons were not found, but this is not related to the messages from the console :-(

**Comment by pre55** [comment]
Struktorizer v3.23-14 works without issues.
downloaded from links:
http://structorizer.fisch.lu/webstart/Structorizer.jnlp
http://www.fisch.lu/Php/download.php?file=structorizer_latest.zip

**Comment by codemanyak** [comment]
That's fine. So we may close this issue for now.
But I'm still puzzled what might have gone wrong with the older versions.
A screen reolution of 1920 x 1080 is nothing extraordinary, I usually work with this very resolution without problems).
The console messages indicate a missing language file, though. Which in turn suggests that the resource path was somehow damaged. And so it explains why the icons couldn't be found, either. It sheds no light, however, to the question what might have compromised the resource finding mechanism.
Thanks for your efforts to clarify the issue, anyway.
