### ISSUE TITLE
Version 3.24-06 Zip download is completely dysfunctional on Windows

### ISSUE THREAD

**Issue by codemanyak** [fesch/Structorizer.Desktop#157]
After unzipping Structorizer.latest.zip, Structorizer.exe doesn't work.
The shell script contains an invalid path. After its correction, the following error messages occur:
```
C:\tools\Structorizer>java -jar Structorizer.app/Contents/Java/Structorizer.jar
Structorizer
Error: A JNI error has occurred, please check your installation and try again
Exception in thread "main" java.lang.NoClassDefFoundError: com/apple/eawt/Applic
ationListener
        at java.lang.Class.getDeclaredMethods0(Native Method)
        at java.lang.Class.privateGetDeclaredMethods(Unknown Source)
        at java.lang.Class.privateGetMethodRecursive(Unknown Source)
        at java.lang.Class.getMethod0(Unknown Source)
        at java.lang.Class.getMethod(Unknown Source)
        at sun.launcher.LauncherHelper.validateMainClass(Unknown Source)
        at sun.launcher.LauncherHelper.checkAndLoadMain(Unknown Source)
Caused by: java.lang.ClassNotFoundException: com.apple.eawt.ApplicationListener
        at java.net.URLClassLoader.findClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        at sun.misc.Launcher$AppClassLoader.loadClass(Unknown Source)
        at java.lang.ClassLoader.loadClass(Unknown Source)
        ... 7 more
```
When I don't extract the entire zip file but just replace the Structorizer.jar file in its original place then Structorizer opens at least but it's still version 3.24-05! (Which is consistent to the version number held in info.plist)

**Comment by fesch** [comment]
You are right. I suppose this is because the Sub of the OSX App changed :-(
I will need to generate a new EXE too ...

**Comment by codemanyak** [comment]
Well, with no regard to the old version, it's just a path problem. The jar files are now all situated in a Java directory directly under Structorizer.app/Contents whereas the Structorízer.exe still expects them in Structorizer.app/Contents/Resources/Java and Structorizer.app/Contents/Resources/Java/lib, respectively. As sson as the jar files are moved to their original places, all works again.
This means that Structorizer.jar also still expects the library jar files in a subdirectory lib at its own level.

**Comment by codemanyak** [comment]
Might it be possible to configure the AppBundler in a way that it uses the old folders? Then the Structorizer.exe (and the poor guy having to find a substitute ;-) might get a grace period...

**Comment by fesch** [comment]
No, that's not possible.

Work in progress ... give me a minute or two ;-)

**Comment by fesch** [comment]
Okay, I've uploaded new packages with corrected .sh files, a new EXE wrapper and a single big & signed JAR file.

**Comment by codemanyak** [comment]
Tataaa! It works. So many thanks for the rapid mending! Was a pretty busy day...

**Comment by fesch** [comment]
The new EXE wrapper has now been created by Launch4J ... just to mention it somewhere ...

**Comment by codemanyak** [comment]
I already wanted to ask. I will have a look whether issue #126 is solved thereby. In case of a missing Jar I get a message already. Now I'm looking for a computer without or with obsolete Java installation in order to see what happens.
