### ISSUE TITLE
Version 24-6 does not start in Linux.

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#159]
Hi,

would test the newest version - many, many thanks for your work, but it didn't start.
Here the output.
`Exception in thread "main" java.lang.UnsupportedClassVersionError: Structorizer : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:800)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:449)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:71)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:361)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:355)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:354)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:308)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)`

Hope that helps
Fine regards
Rolf

**Comment by fesch** [comment]
Structorizer has been compiled with Java 8 (version 52) but you seam to try to run it with a lower version ... 7 oder 6 ?

**Comment by reks99** [comment]
@fesch Hi Bob,

why and when is the java version changed? Version 24-5 runs without problems

Thanks for your quick response.
Rolf

**Comment by fesch** [comment]
I changed it yesterday during the repackaging system. 
Just re-compiled a Java 6 version right now and uploaded it. Please download and try again.

**Comment by reks99** [comment]
@fesch 
Hi Bob.

Now it works. Many thanks again for your fast response too.

Rolf

**Comment by codemanyak** [comment]
@reks99
> Now it works. Many thanks again for your fast response too.

By the way, you should better only use the newest Java version (i. e. 
JavaSE 8), also for security reasons in particular.

**Comment by reks99** [comment]
Hi Kay,

> By the way, you should better only use the newest Java version (i. e. 
> JavaSE 8), also for security reasons in particular.

Java is installed out of the repository of my linux version, so the
maintainer of the java package keep care of the security issues and send
me a new package, if needed.

If I install java by my self I personally have to keep track on new
versions.

Thanks for your suggestion.
Rolf
