### ISSUE TITLE
java.lang.NoSuchMethodError

### ISSUE THREAD

**Issue by cgloeckner** [fesch/Structorizer.Desktop#278]
Hi,
I've got the following exception while startup on Ubuntu:
```
./structorizer.sh 
Exception in thread "main" java.lang.NoSuchMethodError: java.util.HashMap.getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
	at lu.fisch.structorizer.parsers.D7Parser.loadFromINI(D7Parser.java:985)
	at lu.fisch.structorizer.gui.Mainform.loadFromINI(Mainform.java:289)
	at lu.fisch.structorizer.gui.Mainform.create(Mainform.java:124)
	at lu.fisch.structorizer.gui.Mainform.<init>(Mainform.java:585)
	at lu.fisch.structorizer.gui.Mainform.<init>(Mainform.java:578)
	at Structorizer.main(Structorizer.java:145)
```
Additional information:
```
java -version
java version "1.7.0_101"
OpenJDK Runtime Environment (IcedTea 2.6.6) (7u101-2.6.6-0ubuntu0.15.10.1)
OpenJDK 64-Bit Server VM (build 24.95-b01, mixed mode)
```
structorizer is the current latest version (downloaded just a minute ago)
(v3.25 via links below the latest does work)

**Comment by fesch** [comment]
Looks like "java.util.HashMap.getOrDefault" is a Java 1.8 function,which is not Java 1.7 compatible. I will check this ...

**Comment by fesch** [comment]
Could you please try the new version I've uploaded some seconds ago?

**Comment by codemanyak** [comment]
There were some more occurrences of the incriminated method in the code left by Bob's fix. A new Structorizer version is ahead, which is meant to solve the problem completely, now.
(Unfortunately, there are undocumented differences between the Java platforms: Some methods of the Oracle JDK aren't available in OpenJDK. Sorry for lacking tests under different platforms.)

**Comment by codemanyak** [comment]
I dare to close this issue now, version 3.25-05 is delivered
