### ISSUE TITLE
Bug: Batch mode in version 3-25-03 does not work

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#279]
Hi Kay,

I testet the batch export as shell skript with the simple nsd, (shown in the picture) but no output was generated. The command line was _structorizer.sh -x bash Sicherung01-xxx.nsd_ 
![sicherung01](https://cloud.githubusercontent.com/assets/18035140/20030413/c943761e-a364-11e6-8dcf-ab407206bd00.png)

The program (i.e. console-) output is
`Exception in thread "main" java.lang.NoSuchMethodError: java.util.HashMap.getOrDefault(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at lu.fisch.structorizer.generators.BASHGenerator.transform(BASHGenerator.java:508)
        at lu.fisch.structorizer.generators.BASHGenerator.generateCode(BASHGenerator.java:548)
        at lu.fisch.structorizer.generators.Generator.generateCode(Generator.java:1093)
        at lu.fisch.structorizer.generators.Generator.generateCode(Generator.java:1138)
        at lu.fisch.structorizer.generators.BASHGenerator.generateCode(BASHGenerator.java:1001)
        at lu.fisch.structorizer.generators.Generator.exportCode(Generator.java:1593)
        at Structorizer.export(Structorizer.java:304)
        at Structorizer.main(Structorizer.java:124)
`
Fine regards
Rolf

**Comment by codemanyak** [comment]
Thanks for the report. The stack trace identifies this as a sibling of issue #278. I happened to use a convenient HasMap method not considering that they were introduced by Java 8 and that the OpenJDK mostly used under Linux is several Java releases behind. I will systematically look for other ocuurances of this method and have to replace them all.

**Comment by codemanyak** [comment]
Code revision done and filed for the next Structorizer version (3.25-05). Tested under an old OpenSuSe distribution without related bug indications.
