### ISSUE TITLE
bug: structurizer does not open a nsd when as first and only parameter

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#281]
Hi Kay,

the newest version does not open a nsd file if you call the program with the name of a nsd file as first and only argument. Structorizer starts, but does not show the diagram.

The error output is as followed
`
Exception in thread "main" java.lang.NoSuchMethodError: java.util.HashMap.replace(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at lu.fisch.structorizer.parsers.D7Parser.setKeyword(D7Parser.java:1144)
        at lu.fisch.structorizer.parsers.NSDParser.startElement(NSDParser.java:401)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1358)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:274)
        at lu.fisch.structorizer.parsers.NSDParser.parse(NSDParser.java:686)
        at lu.fisch.structorizer.gui.Diagram.openNSD(Diagram.java:1176)
        at Structorizer.main(Structorizer.java:163)`

Fine regards
Rolf

**Comment by codemanyak** [comment]
I bumped into a Java 1.8 method again!
Fix is being prepared.

**Comment by codemanyak** [comment]
Version 3.25-06 is pending for rollout. Excuse me, please, for the trouble.
