### ISSUE TITLE
BUG: When try to generate Code with cli

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#347]
Hi,

With the newest version of structorizer (3.25-05) I get errors with the call:
structorizer.sh -x BASH ./Sicherung_06.nsd

The output was:
Exception in thread "main" java.lang.NoSuchMethodError: java.util.HashMap.replace(Ljava/lang/Object;Ljava/lang/Object;)Ljava/lang/Object;
        at lu.fisch.structorizer.parsers.D7Parser.setKeyword(D7Parser.java:1144)
        at lu.fisch.structorizer.parsers.NSDParser.startElement(NSDParser.java:401)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(AbstractSAXParser.java:509)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(XMLDocumentFragmentScannerImpl.java:1358)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(XMLDocumentFragmentScannerImpl.java:2781)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(XMLDocumentScannerImpl.java:606)
        at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(XMLDocumentFragmentScannerImpl.java:504)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:848)
        at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(XML11Configuration.java:777)
        at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(XMLParser.java:141)
        at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(AbstractSAXParser.java:1213)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(SAXParserImpl.java:642)
        at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(SAXParserImpl.java:326)
        at javax.xml.parsers.SAXParser.parse(SAXParser.java:274)
        at lu.fisch.structorizer.parsers.NSDParser.parse(NSDParser.java:686)
        at Structorizer.export(Structorizer.java:244)
        at Structorizer.main(Structorizer.java:124)

Hope that helps
Rolf

**Comment by codemanyak** [comment]
This report refers to a problem already reported with issues #281 and #282, which had been fixed with version 3.25-06 already. By the way, the current version is 3.26-03!

**Comment by reks99** [comment]
Hi Kay Gürtzig:

> This report refers to a problem already reported with issues #281
> and #282, which had been fixed with version 3.25-06 already.

That's nice.

> By the way, the current version is 3.26-03!

I'm sorry, I have to much "structorizer_latest.zip" sometimes to see,
what is different in the newest version.

Rolf

**Comment by codemanyak** [comment]
> I'm sorry, I have to much "structorizer_latest.zip" sometimes to see, what is different in the newest version.

Sorry for having confused you by too many enhancements and bugfixes... I tell you a trick: On downloading a version, I immediately rename it to reflect the version number (e.g. structorizer_latest.zip --> structorizer_3.26-03.zip), this helps a lot in combination with the changelist :wink:.
