### ISSUE TITLE
NSDParser doesn't check for broken NSD files

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#404]
The NSDParser doesn't seem to do much validation, I guess reading from other XML files may have the same issue.
In the case of opening a "broken" NSD file this leads to a hanging GUI thread:

* start Structorizer
* use open
* use the [attached sample][1] (renamed to nsd before - ignore the defects in there, it is just a broken sample)

You get no error message, no drawing and the "normal" messages:

![grafik](https://cloud.githubusercontent.com/assets/6699539/26099476/2065e42e-3a2b-11e7-9218-9b37299cfc32.png)

Additional the GUI is not drawn correctly any more, for example this happens when you resize the window afterwards:

![grafik](https://cloud.githubusercontent.com/assets/6699539/26099395/d43a75e2-3a2a-11e7-9888-3b3e8d04a135.png)

![grafik](https://cloud.githubusercontent.com/assets/6699539/26099548/527998c0-3a2b-11e7-8858-a46322e9dc08.png)

and this when you use file open recent again;

![grafik](https://cloud.githubusercontent.com/assets/6699539/26099564/61ee60c4-3a2b-11e7-88a5-ed4c55a51093.png)

Checking the console for errors shows the following stack trace after the first Open:

~~~
Error parsing file:/C:/dev/CASE-1.nsd: java.lang.ClassCastException: lu.fisch.structorizer.elements.Instruction cannot be cast to lu.fisch.structorizer.elements.For
java.lang.ClassCastException: lu.fisch.structorizer.elements.Instruction cannot be cast to lu.fisch.structorizer.elements.For
	at lu.fisch.structorizer.parsers.NSDParser.startElement(NSDParser.java:650)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.startElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanStartElement(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl$FragmentContentDriver.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentScannerImpl.next(Unknown Source)
	at com.sun.org.apache.xerces.internal.impl.XMLDocumentFragmentScannerImpl.scanDocument(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XML11Configuration.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.XMLParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.parsers.AbstractSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl$JAXPSAXParser.parse(Unknown Source)
	at com.sun.org.apache.xerces.internal.jaxp.SAXParserImpl.parse(Unknown Source)
	at javax.xml.parsers.SAXParser.parse(Unknown Source)
	at lu.fisch.structorizer.parsers.NSDParser.parse(NSDParser.java:783)
	at lu.fisch.structorizer.gui.Diagram.openNSD(Diagram.java:1468)
	at lu.fisch.structorizer.gui.Diagram.openNsdOrArr(Diagram.java:1442)
	at lu.fisch.structorizer.gui.Diagram.openNSD(Diagram.java:1429)
	at lu.fisch.structorizer.gui.Menu$5.actionPerformed(Menu.java:534)
	at javax.swing.AbstractButton.fireActionPerformed(Unknown Source)
	at javax.swing.AbstractButton$Handler.actionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.fireActionPerformed(Unknown Source)
	at javax.swing.DefaultButtonModel.setPressed(Unknown Source)
	at javax.swing.AbstractButton.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI.doClick(Unknown Source)
	at javax.swing.plaf.basic.BasicMenuItemUI$Handler.mouseReleased(Unknown Source)
	at java.awt.Component.processMouseEvent(Unknown Source)
	at javax.swing.JComponent.processMouseEvent(Unknown Source)
	at java.awt.Component.processEvent(Unknown Source)
	at java.awt.Container.processEvent(Unknown Source)
	at java.awt.Component.dispatchEventImpl(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.LightweightDispatcher.retargetMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.processMouseEvent(Unknown Source)
	at java.awt.LightweightDispatcher.dispatchEvent(Unknown Source)
	at java.awt.Container.dispatchEventImpl(Unknown Source)
	at java.awt.Window.dispatchEventImpl(Unknown Source)
	at java.awt.Component.dispatchEvent(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.awt.EventQueue$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.ArrayIndexOutOfBoundsException: Array index out of range: 0
	at java.util.Vector.get(Unknown Source)
	at lu.fisch.structorizer.elements.Case.draw(Case.java:491)
	at lu.fisch.structorizer.elements.Subqueue.draw(Subqueue.java:177)
	at lu.fisch.structorizer.elements.Root.draw(Root.java:702)
	at lu.fisch.structorizer.elements.Root.draw(Root.java:963)
	at lu.fisch.structorizer.elements.Root.draw(Root.java:976)
	at lu.fisch.structorizer.gui.Diagram.redraw(Diagram.java:1187)
	at lu.fisch.structorizer.gui.Diagram.paintComponent(Diagram.java:1240)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JViewport.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintChildren(Unknown Source)
	at javax.swing.JSplitPane.paintChildren(Unknown Source)
	at javax.swing.JComponent.paint(Unknown Source)
	at javax.swing.JComponent.paintToOffscreen(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paintDoubleBuffered(Unknown Source)
	at javax.swing.RepaintManager$PaintManager.paint(Unknown Source)
	at javax.swing.RepaintManager.paint(Unknown Source)
	at javax.swing.JComponent._paintImmediately(Unknown Source)
	at javax.swing.JComponent.paintImmediately(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at javax.swing.RepaintManager$4.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.paintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.prePaintDirtyRegions(Unknown Source)
	at javax.swing.RepaintManager.access$1200(Unknown Source)
	at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
	at java.awt.event.InvocationEvent.dispatch(Unknown Source)
	at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
	at java.awt.EventQueue.access$500(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.awt.EventQueue$3.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
	at java.awt.EventQueue.dispatchEvent(Unknown Source)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
	at java.awt.EventDispatchThread.run(Unknown Source)
~~~

I'd suggest the following:

* catch the AWT message, do cleanup in the catch/finally
* **don't** do a verification when reading NSDs (or other XML files like parsers.xml) but **add a schema for each XML type and validate the XML file against the schema file before opening it**, refuse to open if the XML file isn't valid

[1]:https://github.com/fesch/Structorizer.Desktop/files/1003939/CASE-1.nsd.txt

**Comment by codemanyak** [comment]
Just as a matter of personal interest: What led to this broken NSD file?

**Comment by GitMensch** [comment]
> Just as a matter of personal interest: What led to this broken NSD file?

My bare hands and a plain editor - I tried to construct something that allows me to create a picture for the the proposed CASE drawing improvement with less manual paint'ing (which I finally did). :-)

The point for this issue was
a) we somehow break the drawing capabilities in these cases
b) a file may be corrupt, coming from a too new version, be manually changed, wrong constructed during the import, ... it is good to have a clear check and reject in these cases instead of bugs that may are not easily to find.

**Comment by codemanyak** [comment]
I tried to equip the SAXParserFactory with the structorizer.xsd but with no effect. Maybe I did something wrong.

**Comment by GitMensch** [comment]
Looks good in general, but isn't [setValidating](https://docs.oracle.com/javase/7/docs/api/javax/xml/parsers/SAXParserFactory.html#setValidating(boolean)) missing?

**Comment by GitMensch** [comment]
The [official tutorial on validation](https://docs.oracle.com/javase/tutorial/jaxp/sax/validation.html) is a little bit confusing, for example it uses [setValidating](https://docs.oracle.com/javase/7/docs/api/javax/xml/parsers/SAXParserFactory.html#setValidating(boolean)) while the JavaDocs say this is only relevant for DTD validation...

But there is one other thing it says that seems relevant:

> **The parser factory must be configured to generate a parser that is namespace-aware as well as validating** [...] understand that schema validation is a namespace-oriented process. Because JAXP-compliant parsers are not namespace-aware by default, it is necessary to set the property for schema validation to work.

Even if this does not help it sounds reasonable to read through the turorial.

**Comment by codemanyak** [comment]
I did, I tried with setting both validating and namespace awareness true - no difference, I get the same cast error induced by optimistic stack content expectations...

If I deactivate all the code in startElement() and endElement() then the only SAX error message is that the `<case>` tag isn't closed (which is of course correct) but the illegal repetition of the `<qFor>` isn't detected, not at least in time.

**Comment by codemanyak** [comment]
If I don't interpret it wrong the the schema object created by the SchemaFactory contains an empty grammar - All te hash tables for complex and simple types are empty. The meta data (home page, file location etc.) is available, though.
The same happens for the plugin.xsd schema I just tried in GENParser. 😞 
No error message, nothing. Just dysfunctional.

**Comment by codemanyak** [comment]
After having overwritten the handling methods `error(SAXParseException exception)` and `fatalError(SAXParseException exception)` it seems to get clearer. I get three otherwise suppressed error messages saying:
```
org.xml.sax.SAXParseException; systemId: file:/D:/SW-Produkte/Structorizer/tests/Issue404_broken_Nsd_file/CASE-1.nsd; lineNumber: 2; columnNumber: 6; Dokument ist ungültig. Keine Grammatik gefunden.
org.xml.sax.SAXParseException; systemId: file:/D:/SW-Produkte/Structorizer/tests/Issue404_broken_Nsd_file/CASE-1.nsd; lineNumber: 2; columnNumber: 6; Document Root-Element "root"muss mit DOCTYPE-Root "null" übereinstimmen.
org.xml.sax.SAXParseException; systemId: file:/D:/SW-Produkte/Structorizer/tests/Issue404_broken_Nsd_file/CASE-1.nsd; lineNumber: 2; columnNumber: 461; cvc-elt.1: Deklaration des Elements 'root' kann nicht gefunden werden.
```
Replacing the (invalid) Html location of the namespace by the local xsd file URL in the broken NSD file doesn't change anything though. I get the impression that the schema is (silently) invalid, though I have no clue why. Usual xsd editors (e.g. Visual Studio) didn't complain at all.

**Comment by codemanyak** [comment]
I leave the analysis for now as it is of little practical use as long as the processed files are correct.

**Comment by GitMensch** [comment]
Yes, please leave it as it is, adding only a comment about this (short and mentioning this issue for details). Any chance to work on #420 ?
