### ISSUE TITLE
structorizer 3.27 does not start

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#450]
Hi
I would test the version 3.27 in my debian jessie (old stable) with openjdk-8 installed, but it does not start.
I get:
_Exception in thread "main" java.lang.UnsupportedClassVersionError: Structorizer : Unsupported major.minor version 52.0
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:803)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:142)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:442)
        at java.net.URLClassLoader.access$100(URLClassLoader.java:64)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:354)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:348)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:347)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:425)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:312)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:358)
        at sun.launcher.LauncherHelper.checkAndLoadMain(LauncherHelper.java:482)_
What can I do?

Fine regards
Rolf

**Comment by fesch** [comment]
Java 8 = Version 52, so this should be fine.

Are you sure you used the Java8 JVM to start Structorizer?

**Comment by reks99** [comment]
Hi Bob.

I found the mistake: When Java8 was installed with the package manager the system did not update the alias for java, so still java7 was used, when java is called.
After manualy correct the link to the java-8 runtime every thing is fine.

Sorry for the noise.
Fine regards
Rolf

**Comment by fesch** [comment]
Great :)
