### ISSUE TITLE
Bug? Too large NSD when opened via command line

### ISSUE THREAD

**Issue by reks99** [fesch/Structorizer.Desktop#455]
Hi,
when i open an existing nsd as a comand line option is enormous enlarged (see attaced image). This did not happen, when open from inside struturizer.
![sicherung_05](https://user-images.githubusercontent.com/18035140/32414117-48b5a6e4-c220-11e7-8416-3c99ec9cdb68.png)
Fine regards
Rolf

**Comment by codemanyak** [comment]
This is due to races on Structorizer start. The scrollpanes generate NullPointerExceptions because some interrelated other controls haven't been established fast enough, while the diagram is already being drawn. Unfortunately we can't control the order of the concurrent drawing and initialization threads - at least I haven't found out yet, how.
The simplest way to "fix" the drawing artefact is twice to press F4.

**Comment by GitMensch** [comment]
> This problem is mentioned in the "known issues" paragraph in the changelog.
> The simplest way to "fix" the drawing artefact is to press F4 twice.

I opt for removing it from the "known issues" and auto-call the redraw function after the file was loaded.

**Comment by codemanyak** [comment]
@GitMensch 
The diagram is drawn after having been loaded. This is still too early, it seems, if the loading was an integral part of starting Structorizer, e.g. by double-clicking an .nsd file or starting it via script with file argument.
I have no idea how we can find out that the initialization of all menu, toolbar, and editor stuff has finished. Then and only then it makes sense to redraw the diagram. The GUI stuff is done by background threads, which is diffcult to get hold of. We don't know in what order the javax.swingRepaintManager creates the menuItems, scrollPanes, toolbars etc. and when the last of them is ready.
And I can't watch them or debug them. So I don't even know in detail why, when and how the diagram is streched to this enormous extension.

**Comment by GitMensch** [comment]
> I have no idea how we can find out that the initialization of all menu, toolbar, and editor stuff has finished. Then and only then it makes sense to redraw the diagram. The GUI stuff is done by background threads, which is difficult to get hold of. We don't know in what order the javax.swingRepaintManager creates the menuItems, scrollPanes, toolbars etc. and when the last of them is ready.

@codemanyak 

I think we actually don't need to find out when the drawing is finished. We just want to do the drawing of the NSD afterwards. Looks like [`invokeLater`][1] (or even [`invokeAndWait`][2]) would do the trick as it tells the Event Dispatch Thread do invoke the code *after* it has finished drawing the other stuff. Wouldn't it?

[2]:https://docs.oracle.com/javase/8/docs/api/javax/swing/SwingUtilities.html#invokeAndWait-java.lang.Runnable-

**Comment by codemanyak** [comment]
I have tried so. All that. Wrapped parts of Diagram.redraw() in an invokeLater() context - with no significantly different behaviour. That's the frustrating thing here. While I don't know exactly what goes wrong it's like shooting in the wild. Sometimes it looks as if a measure had helped but next time the trouble is back.
Besides: As far as I know the java.awt.Component.repaint() method already makes use of a mechanism like invokeLater():

> Repaints this component. 
If this component is a lightweight component, this method causes a call to this component's paint method as soon as possible. Otherwise, this method causes a call to this component's update method as soon as possible. 

So to wrap it one more time is unlikely to help. Swing is known not to be threadsafe.

**Comment by GitMensch** [comment]
No. I don't meant to wrap the `the java.awt.Component.repaint()` method into `invokeLater()` but to do something like the following change:

```java
startup(); // includes writing the GUI
loadfile(argv);
paintdiagram();
```

to 

```java
startup(); // includes writing the GUI
invokeAndWait(new Runnable() {
    @Override 
    public void run() {
        loadfile(argv);
    });
invokeLater(new Runnable() {
    @Override 
    public void run() {
        paintdiagram();
    });
```

In theory this should start the loadfile function only when the GUI is started up already and the paintdiagram function when this loading has finished.

**Comment by codemanyak** [comment]
Thanks for insisting here. Indeed, after having plastered the entire Mainform initialization and the loading of files passed as arguments with sequentializing invokeAndWait chunks and disabled premature drawing calls, eventually I haven't seen uncaught NullPointerExceptions and drawing contortions anymore. At least after some dozen test starts of diagrams that had always caused trouble.
Now it takes a visible moment between the presentation of the empty start diagram and its replacement by the loaded diagram, but the latter looks flawless then.

**Comment by GitMensch** [comment]
@codemanyak I've just started the bugfix branch from IDE and was prompted with (luckily now only) one Exception:

**layoutHScrollbar:**
~~~
Loading now locale: en.txt
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at javax.swing.plaf.basic.BasicScrollBarUI.layoutHScrollbar(BasicScrollBarUI.java:762)
	at javax.swing.plaf.basic.BasicScrollBarUI.layoutContainer(BasicScrollBarUI.java:870)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validate(Container.java:1630)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
~~~

The second start was Exception-free, the third got

**layoutVScrollbar:**
~~~
Loading now locale: en.txt
Loading now locale: en.txt
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
	at javax.swing.plaf.basic.BasicScrollBarUI.layoutVScrollbar(BasicScrollBarUI.java:662)
	at javax.swing.plaf.basic.BasicScrollBarUI.layoutContainer(BasicScrollBarUI.java:866)
	at java.awt.Container.layout(Container.java:1510)
	at java.awt.Container.doLayout(Container.java:1499)
	at java.awt.Container.validateTree(Container.java:1695)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validateTree(Container.java:1704)
	at java.awt.Container.validate(Container.java:1630)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:711)
	at javax.swing.RepaintManager$3.run(RepaintManager.java:709)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at javax.swing.RepaintManager.validateInvalidComponents(RepaintManager.java:708)
	at javax.swing.RepaintManager$ProcessingRunnable.run(RepaintManager.java:1731)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:756)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:76)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:726)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
~~~

Start 4-9 were clean.

Is there something we can do about this last one, too?

**Comment by codemanyak** [comment]
> Is there something we can do about this last one, too?

I know these race execeptions occurring at random on start, and I would be lucky if I knew how to fix them. I had hoped to get rid of them with the fix for this issue here but obviously it was only a partial success. The further functioning of Structorizer isn't compromised and the user won't even notice unless he/she started Structorizer from the console. So it can be tolerated in practise, though it's ugly, of course, and may convey a bad reputation. But still I haven't found a way to nail it.

**Comment by GitMensch** [comment]
OK, just hoped you had an idea how to fix this - in general it got *much* better (when starting hunting down for NullPtrExceptions some months ago I needed to skip several ones before the GUI was even up - and from time to time they showed up during the execution - now I only *seldom* see these and only once at the start), therefore: good work :-)
