### ISSUE TITLE
NullPointerException during startup, killing Menu

### ISSUE THREAD

**Issue by GitMensch** [fesch/Structorizer.Desktop#595]
Normally everything works but from time to time (using unchanged `makeStructorizer`) the following error occurs during startup

~~~
Sep 17, 2018 1:54:44 PM lu.fisch.structorizer.gui.Mainform create
SCHWERWIEGEND: Menu creation thread failed.
java.lang.reflect.InvocationTargetException
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1349)
        at java.awt.EventQueue.invokeAndWait(EventQueue.java:1324)
        at lu.fisch.structorizer.gui.Mainform.create(Mainform.java:264)
        at lu.fisch.structorizer.gui.Mainform.<init>(Mainform.java:1081)
        at lu.fisch.structorizer.gui.Mainform.<init>(Mainform.java:1066)
        at Structorizer.main(Structorizer.java:260)
Caused by: java.lang.NullPointerException
        at javax.xml.validation.SchemaFactory.newSchema(SchemaFactory.java:670)
        at lu.fisch.structorizer.parsers.GENParser.parse(GENParser.java:200)
        at lu.fisch.structorizer.gui.Menu.addPluginMenuItems(Menu.java:1834)
        at lu.fisch.structorizer.gui.Menu.create(Menu.java:718)
        at lu.fisch.structorizer.gui.Menu.<init>(Menu.java:1723)
        at lu.fisch.structorizer.gui.Mainform$2.run(Mainform.java:267)
        at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:301)
        at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
        at java.awt.EventQueue.access$500(EventQueue.java:97)
        at java.awt.EventQueue$3.run(EventQueue.java:709)
        at java.awt.EventQueue$3.run(EventQueue.java:703)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
        at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
        at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
        at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
        at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)

~~~

*If* there's a problem with a specific menu entry for a plugin it would be reasonable to still add the common menu.

Note: I've found the two issues (missing adjustment of makeStructorizer and missing check in GENParser.java), will add a PR for both later.

**Comment by GitMensch** [comment]
Fixed with 7c717381a0b9048a9441b4b366c29750aceecf6b
