### ISSUE TITLE
ClassNotFound Exception

### ISSUE THREAD

**Issue by erka2020** [fesch/Structorizer.Desktop#940]
Starting Structorizer on Windows 10 Java 8 Update 281 fails.
Web Start app thows exception
java.lang.ClassNotFoundException: java.awt.desktop.OpenFilesHandler
	at java.net.URLClassLoader.findClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.findClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at com.sun.jnlp.JNLPClassLoader.loadClass(Unknown Source)
	at java.lang.ClassLoader.loadClass(Unknown Source)
	at Structorizer.main(Structorizer.java:370)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at com.sun.javaws.Launcher.executeApplication(Unknown Source)
	at com.sun.javaws.Launcher.executeMainClass(Unknown Source)
	at com.sun.javaws.Launcher.doLaunchApp(Unknown Source)
	at com.sun.javaws.Launcher.run(Unknown Source)
	at java.lang.Thread.run(Unknown Source)
Install Version doesn't start either.

**Comment by codemanyak** [comment]
This was obvioulsy a consequence of bugfix #912 (which was smuggled into the version 3.30-16 yesterday): Method `Desktop.setOpenFileHandler(OpenFilesHandler openFileHandler)` was only introduced with Java 9. 😞

**Comment by codemanyak** [comment]
I will try something via reflection...

**Comment by codemanyak** [comment]
The issue is not solved as there is no new Structorizer.jar in the product: It starts as version 3.30-16 with Java 11 but not at all with Java 8.

**Comment by codemanyak** [comment]
Just checked with a locally build Strautcorizer.jar for the actual version 3.30-17: It would start on Windows with Java 8.

**Comment by fesch** [comment]
I confirm, it does not start with Java 8 :-(

**Comment by fesch** [comment]
The newly uploaded version starts with Java 8 without any problems.

@erka2020 : Can you confirm?

**Comment by codemanyak** [comment]
Just to corroborate: On my old computer with Java 8 it updates and works fine now.

**Comment by erka2020** [comment]
Yes, i can confirm. 3.30-17 works without any problems. 
Thank you very much - now my pupils can do their homework.
