### ISSUE TITLE
 Problem with execution control

### ISSUE THREAD

**Issue by raulus127** [fesch/Structorizer.Desktop#977]
Hello. I have a problem executing the algorithm. It is stopped in the first block and the execution continues. I tried reinstalling the Structorizer and deleting the temporary files but the problem persists.

**Comment by codemanyak** [comment]
@raulus127 
Could you please provide some context information (OS, Structorizer version), ideally your diagram - or does it apply to any diagrams you try to execute?

**Comment by codemanyak** [comment]
@raulus127 
Unfortunately I can't reproduce your problem. Do you get some error message? Have you checked the content of the log file (`C:\Users\Raul\.structorizer\structorizer0.0.log`)?
In order to exclude the possibility that there might be some systematic problem in your diagrams (something syntactical perhaps) I would like you to attach a minimum nsd file that caused the problem at your site together with the mentioned log file to your next reply. Thanks in advance.

**Comment by raulus127** [comment]
> Unfortunately I can't reproduce your problem. Do you get some error message? Have you checked the content of the log file (`C:\Users\Raul\.structorizer\structorizer0.0.log`)?
> In order to exclude the possibility that there might be some systematic problem in your diagrams (something syntactical perhaps) I would like you to attach a minimum nsd file that caused the problem at your site together with the mentioned log file to your next reply. Thanks in advance.

The execution does not throw any error. Next I give you an image of how the execution is, the nsd file and the log.

**Comment by raulus127** [comment]
> > Unfortunately I can't reproduce your problem. Do you get some error message? Have you checked the content of the log file (`C:\Users\Raul\.structorizer\structorizer0.0.log`)?
> > In order to exclude the possibility that there might be some systematic problem in your diagrams (something syntactical perhaps) I would like you to attach a minimum nsd file that caused the problem at your site together with the mentioned log file to your next reply. Thanks in advance.
> 
> The execution does not throw any error. Next I give you an image of how the execution is, the nsd file and the log.


The execution does not throw any error. Next I give you an image of how the execution is, the nsd file and the log.


```
<?xml version="1.0" encoding="windows-1252" standalone="no"?>
<!DOCTYPE log SYSTEM "logger.dtd">
<log>
<record>
  <date>2021-06-09T09:47:34</date>
  <millis>1623242854272</millis>
  <sequence>0</sequence>
  <logger>Structorizer</logger>
  <level>INFO</level>
  <class>Structorizer</class>
  <method>main</method>
  <thread>1</thread>
  <message>Command line: </message>
</record>
<record>
  <date>2021-06-09T09:47:34</date>
  <millis>1623242854662</millis>
  <sequence>1</sequence>
  <logger>lu.fisch.structorizer.gui.Mainform</logger>
  <level>INFO</level>
  <class>lu.fisch.structorizer.gui.Mainform</class>
  <method>&lt;init&gt;</method>
  <thread>1</thread>
  <message>Structorizer 1 (version 3.31-03) starting up.</message>
</record>
<record>
  <date>2021-06-09T09:47:34</date>
  <millis>1623242854928</millis>
  <sequence>2</sequence>
  <logger>lu.fisch.structorizer.locales.Locale</logger>
  <level>INFO</level>
  <class>lu.fisch.structorizer.locales.Locale</class>
  <method>&lt;init&gt;</method>
  <thread>1</thread>
  <message>Loading now locale: es.txt</message>
</record>
```
![nsd](https://user-images.githubusercontent.com/66838595/121366019-8354d780-c90f-11eb-981a-bc57514ef09c.PNG)
![nsd_run](https://user-images.githubusercontent.com/66838595/121366147-a089a600-c90f-11eb-8c72-3bd20a6683c8.PNG)

**Comment by codemanyak** [comment]
Strange. I tested an equivalent diagram (see screenshot) with the only problem of a (duly) reported index range error, which is caused by your loop, obviously (an array of 10 elements has no valid index 10, the maximum index is 9, such that the loop has to be formulated as `Para i <- 0 hasta 9`):
![grafik](https://user-images.githubusercontent.com/15326471/121368877-af864d80-c93b-11eb-8c55-d0a0ee97d336.png)
![grafik](https://user-images.githubusercontent.com/15326471/121368934-ba40e280-c93b-11eb-8133-4ec19787da09.png)

So I still don't have a clue what's going wrong at your side. The log file does not indeed report any bug.

What could we do know? I guess you have installed Structorizer via the Windows installation assistent? Then you might also download the available [zip package](https://www.fisch.lu/Php/download.php?file=structorizer_latest.zip), unzip it somewhere on your computer, open a console via `cmd.exe` and run the `Structorizer.bat` there. Perhaps we might see some error output on the console?

**Comment by codemanyak** [comment]
Oh, you had closed the issue already - by accident?

**Comment by raulus127** [comment]
> Oh, you had closed the issue already - by accident?

I have surely accidentally closed it.
Indeed, element 10 of the array does not exist. It is an example algorithm to show my students that the elements of an array of size 10 range from 0-9. The example is to show you that.

Anyway, it happens to me with all diagrams. I'm going to test what you tell me to see if I can see the error on the console.

**Comment by raulus127** [comment]
> Strange. I tested an equivalent diagram (see screenshot) with the only problem of a (duly) reported index range error, which is caused by your loop, obviously (an array of 10 elements has no valid index 10, the maximum index is 9, such that the loop has to be formulated as `Para i <- 0 hasta 9`):
> ![grafik](https://user-images.githubusercontent.com/15326471/121368877-af864d80-c93b-11eb-8c55-d0a0ee97d336.png)
> ![grafik](https://user-images.githubusercontent.com/15326471/121368934-ba40e280-c93b-11eb-8133-4ec19787da09.png)
> 
> So I still don't have a clue what's going wrong at your side. The log file does not indeed report any bug.
> 
> What could we do know? I guess you have installed Structorizer via the Windows installation assistent? Then you might also download the available [zip package](https://www.fisch.lu/Php/download.php?file=structorizer_latest.zip), unzip it somewhere on your computer, open a console via `cmd.exe` and run the `Structorizer.bat` there. Perhaps we might see some error output on the console?


I attach the error that is displayed in console.

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.plaf.basic.BasicScrollBarUI.layoutVScrollbar(Unknown Source)
        at javax.swing.plaf.basic.BasicScrollBarUI.layoutContainer(Unknown Source)
        at java.awt.Container.layout(Unknown Source)
        at java.awt.Container.doLayout(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validate(Unknown Source)
        at javax.swing.RepaintManager$3.run(Unknown Source)
        at javax.swing.RepaintManager$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.text.DefaultHighlighter.removeAllHighlights(Unknown Source)
        at lu.fisch.structorizer.gui.Diagram.highlightCodeForSelection(Diagram.java:2003)
        at lu.fisch.structorizer.gui.Diagram.access$800(Diagram.java:331)
        at lu.fisch.structorizer.gui.Diagram$6.run(Diagram.java:7714)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "Player" java.lang.NullPointerException
        at javax.swing.text.DefaultHighlighter.removeAllHighlights(Unknown Source)
        at lu.fisch.structorizer.gui.Diagram.redraw(Diagram.java:1714)
        at lu.fisch.structorizer.executor.Executor.checkBreakpoint(Executor.java:4996)
        at lu.fisch.structorizer.executor.Executor.step(Executor.java:5046)
        at lu.fisch.structorizer.executor.Executor.execute(Executor.java:1851)
        at lu.fisch.structorizer.executor.Executor.execute(Executor.java:1591)
        at lu.fisch.structorizer.executor.Executor.run(Executor.java:3137)
        at java.lang.Thread.run(Unknown Source)

**Comment by codemanyak** [comment]
By the way: Your declaration does not exactly do what you intend. It is rather surprising for me that Structorizer tolerated it. The correct syntax to declare an array of ten elements would follow the Pascal style: `var v1: array [0..9] of int`. But it has no effect, actually. var v1[10] creates indeed an array of 11 elements all initialized to 0 because Structorizer produces an array of sufficient size as soon as it bumps into some writing attempt attempt to an array element.
The actually limiting step was the initialisation with `{1,4,7,...}`. This overrides all previous declarations or assignments. Structorizer needs declarations only for record or enum types, and not even always there. An unambiguous initialisation is usually sufficient.

**Comment by raulus127** [comment]
Sure, my intention is to show you the error. However, the execution problem occurs with all diagrams. I pass him another.

Design
![pp1](https://user-images.githubusercontent.com/66838595/121374997-c0709800-c916-11eb-8967-b42beb9a9699.PNG)

Run
![pp1_run](https://user-images.githubusercontent.com/66838595/121375000-c1092e80-c916-11eb-948d-6bb9b3327e01.PNG)

Error:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.text.DefaultHighlighter.removeAllHighlights(Unknown Source)
        at lu.fisch.structorizer.gui.Diagram.highlightCodeForSelection(Diagram.java:2003)
        at lu.fisch.structorizer.gui.Diagram.access$800(Diagram.java:331)
        at lu.fisch.structorizer.gui.Diagram$6.run(Diagram.java:7714)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "Player" java.lang.NullPointerException
        at javax.swing.text.DefaultHighlighter.removeAllHighlights(Unknown Source)
        at lu.fisch.structorizer.gui.Diagram.redraw(Diagram.java:1714)
        at lu.fisch.structorizer.executor.Executor.checkBreakpoint(Executor.java:4996)
        at lu.fisch.structorizer.executor.Executor.step(Executor.java:5046)
        at lu.fisch.structorizer.executor.Executor.execute(Executor.java:1851)
        at lu.fisch.structorizer.executor.Executor.execute(Executor.java:1591)
        at lu.fisch.structorizer.executor.Executor.run(Executor.java:3137)
        at java.lang.Thread.run(Unknown Source)

**Comment by codemanyak** [comment]
> Exception in thread "Player" java.lang.NullPointerException
> at javax.swing.text.DefaultHighlighter.removeAllHighlights(Unknown Source)
> at lu.fisch.structorizer.gui.Diagram.redraw(Diagram.java:1714)
> at lu.fisch.structorizer.executor.Executor.checkBreakpoint(Executor.java:4996)
> at lu.fisch.structorizer.executor.Executor.step(Executor.java:5046)
> at lu.fisch.structorizer.executor.Executor.execute(Executor.java:1851)
> at lu.fisch.structorizer.executor.Executor.execute(Executor.java:1591)
> at lu.fisch.structorizer.executor.Executor.run(Executor.java:3137)
> at java.lang.Thread.run(Unknown Source)

Oh great, this helps indeed. There is some problem in the code preview, it seems. What favourite export language have you chosen?

**Comment by codemanyak** [comment]
This is still mysterious. The code of method `lu.fisch.structorizer.gui.Diagram.redraw(Element)` checks if the code preview highlighter is null before it calls method `removeAllHighlights()`. So it must be some inconsistency within the code preview highlighter that has never occurred before.
I think my only option for now might be to enclose the faulty method in a try block as workaround while I can't reproduce the circumstances of this apparition.

**Comment by raulus127** [comment]
> > Exception in thread "Player" java.lang.NullPointerException
> > at javax.swing.text.DefaultHighlighter.removeAllHighlights(Unknown Source)
> > at lu.fisch.structorizer.gui.Diagram.redraw(Diagram.java:1714)
> > at lu.fisch.structorizer.executor.Executor.checkBreakpoint(Executor.java:4996)
> > at lu.fisch.structorizer.executor.Executor.step(Executor.java:5046)
> > at lu.fisch.structorizer.executor.Executor.execute(Executor.java:1851)
> > at lu.fisch.structorizer.executor.Executor.execute(Executor.java:1591)
> > at lu.fisch.structorizer.executor.Executor.run(Executor.java:3137)
> > at java.lang.Thread.run(Unknown Source)
> 
> Oh great, this helps indeed. There is some problem in the code preview, it seems. What favourite export language have you chosen?

I'm not sure I understand what you mean.

language : Java, C, Pascal, etc?

**Comment by raulus127** [comment]
> > I'm not sure I understand what you mean.
> > language : Java, C, Pascal, etc?
> 
> Yes. You can choose a favourite programming language for export and code preview panel, either via the Export Option dialog (Preferencias > Exportación ...) or, way easier, by the context menu of the code preview itself. Which of the available export languages is selected (well I happened to test all, none of them caused trouble with your diagram)?
> Anyway, I put a Structorizer.jar file here with a temporary workaround. Would you mind replacing the one in the subdirectory `Structorizer\Structorizer.app\Contents\Java\` of your recently downloaded unzipped version and tell me whether there are still problems when you run the `Structorizer.bat`?
> 
> [Structorizer.zip](https://github.com/fesch/Structorizer.Desktop/files/6624924/Structorizer.zip)


Oh well! The export language I have selected is: Java. Now I prove what you happened to me.

**Comment by codemanyak** [comment]
Just some additional questions:

- Java 8 update 291 was released by ends of April. Do you know when it was installed on your computer, and have you successfully worked with Structorizer before? Maybe the Oracle patch has some flaws. I am working on AdoptOpenJDK 11 and there has not been such a problem.
- Does the code preview work for your diagrams (without execution)? And does the mutually synchronized highlighting work, i.e. does the related code section occur in bright yellow when you select an element and vice versa?

**Comment by raulus127** [comment]
> Yes. You can choose a favourite programming language for export and code preview panel, either via the Export Option dialog (Preferencias > Exportación ...) or, way easier, by the context menu of the code preview itself. Which of the available export languages is selected (well I happened to test all, none of them caused trouble with your diagram)?
> Anyway, I put a Structorizer.jar file here with a temporary workaround. Would you mind replacing the one in the subdirectory `Structorizer\Structorizer.app\Contents\Java\` of your recently downloaded unzipped version and tell me whether there are still problems when you run the `Structorizer.bat`?

Replacing the file you sent me works fine. 
Although this appears on the console:

Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.plaf.basic.BasicScrollBarUI.layoutHScrollbar(Unknown Source)
        at javax.swing.plaf.basic.BasicScrollBarUI.layoutContainer(Unknown Source)
        at java.awt.Container.layout(Unknown Source)
        at java.awt.Container.doLayout(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validateTree(Unknown Source)
        at java.awt.Container.validate(Unknown Source)
        at javax.swing.RepaintManager$3.run(Unknown Source)
        at javax.swing.RepaintManager$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at javax.swing.RepaintManager.validateInvalidComponents(Unknown Source)
        at javax.swing.RepaintManager$ProcessingRunnable.run(Unknown Source)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.text.DefaultHighlighter.addHighlight(Unknown Source)
        at lu.fisch.structorizer.gui.Diagram.highlightCodeForElement(Diagram.java:2075)
        at lu.fisch.structorizer.gui.Diagram.highlightCodeForSelection(Diagram.java:2034)
        at lu.fisch.structorizer.gui.Diagram.access$10(Diagram.java:2010)
        at lu.fisch.structorizer.gui.Diagram$6.run(Diagram.java:7746)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)
Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
        at javax.swing.text.DefaultHighlighter.addHighlight(Unknown Source)
        at lu.fisch.structorizer.gui.Diagram.highlightCodeForElement(Diagram.java:2075)
        at lu.fisch.structorizer.gui.Diagram.highlightCodeForSelection(Diagram.java:2034)
        at lu.fisch.structorizer.gui.Diagram.access$10(Diagram.java:2010)
        at lu.fisch.structorizer.gui.Diagram$6.run(Diagram.java:7746)
        at java.awt.event.InvocationEvent.dispatch(Unknown Source)
        at java.awt.EventQueue.dispatchEventImpl(Unknown Source)
        at java.awt.EventQueue.access$500(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.awt.EventQueue$3.run(Unknown Source)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(Unknown Source)
        at java.awt.EventQueue.dispatchEvent(Unknown Source)
        at java.awt.EventDispatchThread.pumpOneEventForFilters(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForFilter(Unknown Source)
        at java.awt.EventDispatchThread.pumpEventsForHierarchy(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.pumpEvents(Unknown Source)
        at java.awt.EventDispatchThread.run(Unknown Source)

**Comment by codemanyak** [comment]
@raulus127 
Many thanks. The stacktrace tells me that there are indeed fundamental problems in the highlighting mechanism of the code preview text area:

> ...
> Exception in thread "AWT-EventQueue-0" java.lang.NullPointerException
> at javax.swing.text.DefaultHighlighter.addHighlight(Unknown Source)
> at lu.fisch.structorizer.gui.Diagram.highlightCodeForElement(Diagram.java:2075)
> at lu.fisch.structorizer.gui.Diagram.highlightCodeForSelection(Diagram.java:2034)
> at lu.fisch.structorizer.gui.Diagram.access$10(Diagram.java:2010)
> at lu.fisch.structorizer.gui.Diagram$6.run(Diagram.java:7746)
> at java.awt.event.InvocationEvent.dispatch(Unknown Source)
> ...

But unfortunately this will mean that on systems with this problem the code preview highlighting will rather fail to work. But at least the remaining product should not suffice froom it.

**Comment by raulus127** [comment]
> Just some additional questions:
> 
> * Java 8 update 291 was released by ends of April. Do you know when it was installed on your computer, and have you successfully worked with Structorizer before? Maybe the Oracle patch has some flaws. I am working on AdoptOpenJDK 11 and there has not been such a problem.
> * Does the code preview work for your diagrams (without execution)? And does the mutually synchronized highlighting work, i.e. does the related code section occur in bright yellow when you select an element and vice versa?


Two weeks ago I used it without any problem. I installed it at the beginning of June.
On the other, selecting a block works. I can select it and it looks brilliant.

**Comment by codemanyak** [comment]
Okay I extended the workaround. The problem may have been caused by some GUI initialization hazard we haven't been able to fix by now. A new product version is due now and will contain the fix.

**Comment by raulus127** [comment]
> Okay I extended the workaround. The problem may have been caused by some GUI initialization hazard we haven't been able to fix by now. A new product version is due now and will contain the fix.


Thank you very much for all the help! I am a professor at UTN (National Technological University of Argentina) and I use Structorizer in the subject of Computer Science I of the first year of electronic engineering to teach algorithms. Again, thank you very much for your help !!!

**Comment by codemanyak** [comment]
@raulus127 
I guess version 3.31-04 solved your problem. And I am really glad we could help and that Structorizer seems to be an appreciated tool for teaching algorithms a your university, too.
But please let me take the opportunity to draw your attention to the decision made with issue #944: It is very likely that the next version (3.31-05) may already require Java 11 to run. (You will certainly have seen the respective message on starting Structorizer.) Would that cause a problem for you there?

**Comment by raulus127** [comment]
> @raulus127
> I guess version 3.31-04 solved your problem. And I am really glad we could help and that Structorizer seems to be an appreciated tool for teaching algorithms a your university, too.
> But please let me take the opportunity to draw your attention to the decision made with issue #944: It is very likely that the next version (3.31-05) may already require Java 11 to run. (You will certainly have seen the respective message on starting Structorizer.) Would that cause a problem for you there?

Thank you very much for your valuable help. The update to Java 11 is not a problem since I will ask the maintenance department to install it on all the computers in the faculty laboratories. Again thank you very much.
